name: ü´• deploy-player-playground
on:
  workflow_call:
    inputs:
      aws-account-id:
        type: string
      aws-region:
        type: string
      certificate-arn-wildcard:
        type: string
      domain:
        type: string
      log-level:
        type: string
      stage-name:
        type: string
jobs:
  deploy-player-playground:
    runs-on: ubuntu-latest
    environment:
      # ETX Relaxnews account is all in one
      name: ci_etx-production
    container:
      image: node:18-alpine
    env:
      AWS_ACCOUNT_ID: '${{ inputs.aws-account-id }}'
      AWS_REGION: '${{ inputs.aws-region }}'
      CERTIFICATE_ARN_WILDCARD: '${{ inputs.certificate-arn-wildcard }}'
      DOMAIN: '${{ inputs.domain }}'
      LOG_LEVEL: '${{ inputs.log-level }}'
      STAGE_NAME: '${{ inputs.stage-name }}'
    steps:
    - name: Install alpine packages
      run: |
        rm -f .env
        apk add --no-cache tar git python3 aws-cli
        ln -sf python3 /usr/bin/python
        python3 -m venv .venv
        . .venv/bin/activate
        python3 -m ensurepip
    - name: Setup Git
      run: git config --global --add safe.directory /__w/product-voxa/product-voxa
    - name: ‚¨áÔ∏è Checkout
      id: checkout
      uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: '${{ vars.AWS_ACCESS_KEY_ID }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        aws-region: 'eu-west-1'
    - name: ü•° Setup pnpm
      id: setup-pnpm
      uses: pnpm/action-setup@v3
      with:
        version: latest-8
        run_install: false
    - name: ü™¢ Setup node
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'pnpm'
    - name: üöÄ Deploy to AWS
      run: |
        pnpm install --ignore-scripts
        pnpm exec lerna run build --scope @voxa/dns
        pnpm player-playground:deploy --stage $STAGE_NAME
